### ISSUE TITLE
[Request] A portrait full screen mode for VVS videos 

### ISSUE THREAD

**Issue by GijsTimmers** [jariz/Dumpert#15]
Currently, the full screen button will make the video run in full screen, in landscape mode. Sadly, a lot of videos uploaded to Dumpert are recorded vertically. If I press the full screen button on those videos, the vertical video will be displayed in landscape mode, and remain pretty small. My request is to develop some sort of portrait full screen button so that VVS videos can be appreciated as well.

**Comment by CytoDev** [comment]
@GijsTimmers: This is doable by querying the height and width of the video and rotating it accordingly. Will test this tonight with [this video](http://media.dumpert.nl/tablet/91325e34_Zelfbouw_slimme_spiegel.mp4.mp4.mp4). Thankfully this is easily implemented since we're using [Android's "native" MediaPlayer](https://github.com/jariz/Dumpert/blob/master/Dumpert/src/main/java/io/jari/dumpert/activities/VideoActivity.java#L6).  
  
[Reference](https://developer.android.com/reference/android/media/MediaPlayer.html#pubmethods)

**Comment by jariz** [comment]
@CytoDev maybe file a PR?

**Comment by GijsTimmers** [comment]
It works! Very nice, and thank you.

![screenshot_2016-01-06-23-12-04](https://cloud.githubusercontent.com/assets/972314/12156431/368ecbda-b4cb-11e5-97c4-e7eb46e7b1b2.png)
