### ISSUE TITLE
Follow usernames in comments.

### ISSUE THREAD

**Issue by GijsTimmers** [jariz/Dumpert#33]
This may be pretty hard to implement. I don't think that this one is really necessary but it would be a nice feature to set DR apart from the official Dumpert app.

Every so often, users respond to each other in comments. Or they may mention another user. Request: when a username gets detected, make it 'clickable'. When clicked, scroll the comments section to that comment.

**Comment by CytoDev** [comment]
Should be doable. If the corresponding list of comments has actual references.

**Comment by CytoDev** [comment]
I would say the `comment.content` needs to be scanned for @ references that link to the `comment.author` of another comment. The scroll position could be easily found if it is already cached in the RecyclerView. However, if said user is an active commenter with multiple comments on the same item it might become a somewhat harder issue since we don't know what comment it links to.  
  
To give you an idea of how Dumpert handles the comments and why it would be hard if multiple comments are made by the same person see [this](http://dumpcomments.geenstijl.nl/6710053_76c45254.js).

**Comment by CytoDev** [comment]
I'm tempted to close this as impossible. The very nature of a RecyclerView makes it impossible to know what items are out of view, and multiple comments by the same user would only make it harder...  
  
@jariz, thoughts?

**Comment by jariz** [comment]
How so? We know the index of the comment we're searching for, so all that's left is making the RV scroll to said comment.
```
rv.getLayoutManager().scrollToPosition(index);
```

**Comment by CytoDev** [comment]
Most recent from where, current scroll position? Even so, how would you go about filtering `@ mentions` from regular content?

**Comment by jariz** [comment]
Didn't think about that, but then again, I don't really think this issue is worth all this trouble either way, as it's something the real dumpert site itself doesn't even have.

**Comment by CytoDev** [comment]
@jariz so... We close it? Put it in a backlog? Ignore every comment made on this thread in the future? Go and have a beer?

**Comment by jariz** [comment]
Eh, close it.

**Comment by jariz** [comment]
@CytoDev We need to set up a chat or something probably,  but in the meantime, how's the voting going? Think that's the last thing left, and I kind of want to relaunch it again.

**Comment by CytoDev** [comment]
@jariz Voting is a tough cookie... I kind of stopped working on it for a while, to clear my mind.  
You can read up on my findings in issue #35.  
  
Chat, well... You can easily find my Skype and you already have my email address. You *could* add me on WhatsApp if you really wanted to, but that would have to be discussed elsewhere.
