### ISSUE TITLE
Can't download Dumpert Reader from Play Store

### ISSUE THREAD

**Issue by GijsTimmers** [jariz/Dumpert#7]
https://play.google.com/store/search?q=dumpert%20reader

doesn't give any results.

Can I download the APK somewhere else?

Also: https://play.google.com/store/apps/details?id=io.jari.dumpert&hl=nl still works, which is strange.

**Comment by jariz** [comment]
Yeah, GeenStijl requested me to take it down. All I can say is that they
have good reasons.

**Comment by GijsTimmers** [comment]
That's a shame. Will this repo stay up?

**Comment by CytoDev** [comment]
@GijsTimmers, you can download the current test build from [my pre-release](https://github.com/CytoDev/Dumpert/releases/tag/1.1.3). It does not have the fixes introduced in [#5747455](https://github.com/CytoDev/Dumpert/commit/574745583054283737f78e74e1c21de8760a3442), so text on the cards renders white on white.  
  
Since it isn't signed with the same key the original app is you will be prompted to purge all user data related to the Dumpert Reader. This is hardly a problem though, there really isn't anything aside from caching stored as far as I can tell.  
  
You can also wait until @jariz puts the fixes in his repo, which he was going to do yesterday evening.

**Comment by GijsTimmers** [comment]
Works. Thank you very much.

**Comment by jariz** [comment]
Repo will stay up, see #11 for future plans.
